// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnzTYM-isPGLwTuaSU3Whz3w3jhYPJfv4',
    appId: '1:769869240816:web:76d85d1e804b6585306535',
    messagingSenderId: '769869240816',
    projectId: 'quran-with-tajweed-2212e',
    authDomain: 'quran-with-tajweed-2212e.firebaseapp.com',
    storageBucket: 'quran-with-tajweed-2212e.firebasestorage.app',
    measurementId: 'G-N87VV3QCNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKKQVr2AvEq8oyohGJDllz17FfVyN3wU',
    appId: '1:769869240816:android:297ab5df622cea71306535',
    messagingSenderId: '769869240816',
    projectId: 'quran-with-tajweed-2212e',
    storageBucket: 'quran-with-tajweed-2212e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJaErt_o-1Ce9mXLFGXGemv0xH7DRoGI',
    appId: '1:769869240816:ios:ea197ff327836a53306535',
    messagingSenderId: '769869240816',
    projectId: 'quran-with-tajweed-2212e',
    storageBucket: 'quran-with-tajweed-2212e.firebasestorage.app',
    iosBundleId: 'com.example.tajweedAndQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNJaErt_o-1Ce9mXLFGXGemv0xH7DRoGI',
    appId: '1:769869240816:ios:ea197ff327836a53306535',
    messagingSenderId: '769869240816',
    projectId: 'quran-with-tajweed-2212e',
    storageBucket: 'quran-with-tajweed-2212e.firebasestorage.app',
    iosBundleId: 'com.example.tajweedAndQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnzTYM-isPGLwTuaSU3Whz3w3jhYPJfv4',
    appId: '1:769869240816:web:2f1af83e5dc63864306535',
    messagingSenderId: '769869240816',
    projectId: 'quran-with-tajweed-2212e',
    authDomain: 'quran-with-tajweed-2212e.firebaseapp.com',
    storageBucket: 'quran-with-tajweed-2212e.firebasestorage.app',
    measurementId: 'G-R5YKDHCD7B',
  );

}